defaults:
  - model: baseline
  - metrics: example
  - datasets: example_eval # we do not want to run inference on training data
  - dataloader: example
  - transforms: example_only_instance #example
  - _self_
inferencer:
  device_tensors: ["data_object", "labels"] # which tensors should be on device (ex. GPU)
  device: auto # device name or "auto"
  save_path: "example" # any name here, can be a dataset name
  seed: 1
  from_pretrained: "saved/testing/model_best.pth" # path to the pretrained model saved/testing/model_best.pth
text_encoder:
  _target_: src.text_encoder.CTCTextEncoder
  use_bpe: false
  lm_path: "src/model/lm/librispeech.binary"
  beam_width: 100
  lm_weight: 0.1
  length_penalty: 0.3
